version: '2'

services:  
  web:
    container_name: web
    image: project:1.0
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./..:/var/www/html/app/projectname
    networks:
      - web-net
  db:
    container_name: db
    image: mysql:5.6
    restart: always
    volumes:
      - ./../mysql:/var/lib/mysql
      - ./mysql:/etc/mysql
    #  - ./init_db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
    ports:
      - 3306:3306
    networks:
      - web-net
networks:
  web-net: