version: '2'

services:  
  web:
    container_name: web
    image: web:1.0
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../web:/var/www/html/app/
      - ./_initsh/web:/tmp/_initsh
      - ./../_logs/web:/tmp/logs
    networks:
      - -net
    command: >
      bash -c "sh /tmp/_initsh/init.sh"
  db:
    container_name: db
    image: mysql:5.6
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./../mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - 3306:3306
    networks:
      - -net
  mqtt:
    container_name: mqtt
    image: mqtt:1.0
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 8883:8883
      - 9001:9001
    volumes:
      - ./_initsh/mqtt/mosquitto:/etc/mosquitto
      - ./_initsh/mqtt:/tmp/_initsh
      - ./../_logs/mqtt:/tmp/logs
    networks:
      - -net
    command: >
      bash -c "sh /tmp/_initsh/init.sh"
  mongodb:
    container_name: _mongodb
    image: mongo:3.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD:
    depends_on:
      - db
    ports:
      - 27017:27017
    networks:
      - project-net
networks:
  project-net: