FROM ubuntu:16.04

MAINTAINER Corey <coreyborad@hotmail.com.tw>

# PHP7.1
RUN apt-get update && apt-get install -y software-properties-common \
    python-software-properties \
    locales
RUN locale-gen en_US.UTF-8
RUN export LANG=en_US.UTF-8    
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
RUN apt-get update
RUN apt-get install -y \
    apache2 \
    php7.1 \
    libapache2-mod-php7.1 \
    php7.1-mbstring \
    php7.1-bcmath \
    php7.1-mysql \
    php7.1-gd \
    php7.1-curl \
    php7.1-json \
    php7.1-cgi \
    php7.1-pdo \
    php7.1-zip \
    cron
RUN apt-get install -y php-memcached
RUN apt-get install -y php7.1-xml
RUN a2enmod php7.1
RUN a2enmod rewrite
RUN a2enmod headers
RUN mkdir -p /var/www/html/app
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php/7.1/apache2/php.ini
RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php/7.1/apache2/php.ini
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
COPY apache/apache_config.conf /etc/apache2/sites-enabled/000-default.conf
RUN sed -i '/session    required     pam_loginuid.so/c\#session    required   pam_loginuid.so' /etc/pam.d/cron
RUN ln -snf /usr/share/zoneinfo/'Asia/Taipei' /etc/localtime
RUN echo 'Asia/Taipei' > /etc/timezone

# Open port
EXPOSE 80
EXPOSE 443